version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: kultscraper-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=scraperDB
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    networks:
      - kultscraper-network
volumes:
  mongodb_data:
networks:
  kultscraper-network:
    driver: bridge
